spring.application.name=quicktask

jwt.secret=4a8f3b2c9d1e6f7a0b5c8d2e4f9a1b3c6d8e0f2a4b7c9d1e3f5a7b0c2d4e6f8a
jwt.expiration=86400000

#springDataSourceConfigration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true